### ISSUE TITLE
Intent.Extras is always null

### ISSUE THREAD

**Issue by Gimly** [erdennis13/FirebaseNotificationHub#1]
Hi @erdennis13,

Thanks a lot for this very useful sample. Unfortunately I can't get it to run correctly. When I start the application in debug mode, I can see that the Intent.Extras are always null. If I understand correctly that means that the two other services `FirebaseIIDService` and `NHubFirebase` are never started. I can also see that they aren't because no breakpoint in it are triggered.

Would you have an idea as to why that would be?

I also get the following error if I try going further:

```
Device registration failed with error Default FirebaseApp is not initialized in this process com.xamarin.nhub. Make sure to call FirebaseApp.initializeApp(Context) first.
```

**Comment by ethanis** [comment]
@Gimly I've seen with the resources not being generated correctly from google-services.json before. Can you try removing it from your project and adding it back in (build action | GoogleServicesJson)?

Have you updated the file to point to your Firebase instance?

**Comment by Gimly** [comment]
Thanks for your answer, I just tried that, but I still have the same issue.

I did replace the google-services.json by my own file that I downloaded from my Firebase instance.

**Comment by ethanis** [comment]
Weird, I'm not able to reproduce that. Can you try the following:
 1. Force the android resource designer to update (open a xml resource, make any change and save the file)
 2. Delete the app from your device
 3. Clean, rebuild and deploy the app

**Comment by Gimly** [comment]
Thanks for your help, I finally managed to get everything working as expected. One thing that got me ages to understand was that notifications were simply not functional in the Android Emulator... Everything was much clearer once I switched to a real Android device.
